# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  schedule:
    - cron: '5 * * * *'

jobs:
  activeAirports:
    name: Active Airports JSON
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with: 
        ssh-key: ${{ secrets.GITHUBTOKEN }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: node activeAirports.js
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.co
        git add activeAirports.json
        git commit -m "activeAirports JSON"
        git push